import { _decorator, Component, JsonAsset, TextAsset } from 'cc';
import { GameEvent, gameEvents } from '../core/GameEvents';
import {
    HMCompactLevelData,
    HMLevelData,
    RuntimeSpawnRecord,
} from './LevelDataTypes';
import { simpleDecryptContent } from './SimpleDecrypt';

const { ccclass, property } = _decorator;

@ccclass('LevelDataLoader')
export class LevelDataLoader extends Component {
    @property({ type: JsonAsset, tooltip: 'Recommended for final build: H_T_2.compact.json generated by tools/compact-level.js.' })
    public compactLevel: JsonAsset | null = null;

    @property({ type: TextAsset, tooltip: 'Optional compact text asset: H_T_2.compact.txt' })
    public compactLevelText: TextAsset | null = null;

    @property({ type: TextAsset, tooltip: 'Optional fallback: original encrypted H_T_2.txt from HM Games.' })
    public encryptedLevel: TextAsset | null = null;

    @property({ tooltip: 'If both are assigned, use compactLevel or compactLevelText to reduce size and parsing cost.' })
    public preferCompact = true;

    @property({ tooltip: 'Automatically load in start().' })
    public autoLoad = true;

    private _records: RuntimeSpawnRecord[] = [];
    private _levelName = '';

    public get records(): ReadonlyArray<RuntimeSpawnRecord> {
        return this._records;
    }

    public get levelName(): string {
        return this._levelName;
    }

    protected start(): void {
        if (this.autoLoad) {
            this.loadLevel();
        }
    }

    public loadLevel(): void {
        this._records.length = 0;

        try {
            if (this.preferCompact && (this.compactLevelText || this.compactLevel)) {
                this.loadCompact();
            } else if (this.encryptedLevel) {
                this.readEncrypted(this.encryptedLevel.text);
            } else if (this.compactLevelText || this.compactLevel) {
                this.loadCompact();
            } else {
                console.error('[LevelDataLoader] Assign compactLevelText, compactLevel, or encryptedLevel in Inspector.');
                return;
            }

            gameEvents.emit(GameEvent.LEVEL_DATA_READY, this);
        } catch (error) {
            console.error('[LevelDataLoader] Failed to load level.', error);
        }
    }

    private loadCompact(): void {
        if (this.compactLevelText) {
            const data = JSON.parse(this.compactLevelText.text) as HMCompactLevelData;
            this.readCompact(data);
        } else if (this.compactLevel) {
            this.readCompact(this.compactLevel.json as HMCompactLevelData);
        }
    }

    private readCompact(data: HMCompactLevelData): void {
        if (!data || data.v !== 1 || !Array.isArray(data.ids) || !Array.isArray(data.items)) {
            throw new Error('Unsupported compact level format.');
        }
        if (data.items.length % 7 !== 0) {
            throw new Error('Compact item array length must be divisible by 7.');
        }

        this._levelName = data.n || 'HM_Level';
        for (let i = 0; i < data.items.length; i += 7) {
            const idIndex = data.items[i];
            const id = data.ids[idIndex];
            if (id === undefined) {
                continue;
            }

            this._records.push({
                id,
                px: data.items[i + 1],
                py: data.items[i + 2],
                pz: data.items[i + 3],
                rx: data.items[i + 4],
                ry: data.items[i + 5],
                rz: data.items[i + 6],
            });
        }
    }

    private readEncrypted(text: string): void {
        const decrypted = simpleDecryptContent(text);
        const data = JSON.parse(decrypted) as HMLevelData;
        this._levelName = data.name || 'HM_Level';

        for (let groupIndex = 0; groupIndex < data.listItemSpawns.length; groupIndex++) {
            const group = data.listItemSpawns[groupIndex];
            for (let spawnIndex = 0; spawnIndex < group.listSpawnDatas.length; spawnIndex++) {
                const spawn = group.listSpawnDatas[spawnIndex];
                this._records.push({
                    id: group.id,
                    px: spawn.p.x,
                    py: spawn.p.y,
                    pz: spawn.p.z,
                    rx: spawn.r.x,
                    ry: spawn.r.y,
                    rz: spawn.r.z,
                });
            }
        }
    }
}
