export interface LevelVec3Data {
    x: number;
    y: number;
    z: number;
}

export interface LevelSpawnData {
    p: LevelVec3Data;
    r: LevelVec3Data;
    s: LevelVec3Data;
    kinematic: boolean;
}

export interface LevelItemSpawnGroup {
    id: string;
    listSpawnDatas: LevelSpawnData[];
}

export interface HMLevelData {
    listItemSpawns: LevelItemSpawnGroup[];
    listFenceDatas: unknown[];
    name: string;
    hideFlags: number;
}

/** Compact format generated by tools/compact-level.js. */
export interface HMCompactLevelData {
    v: number;
    n: string;
    ids: string[];
    /** Repeated: idIndex, px, py, pz, rx, ry, rz */
    items: number[];
}

export interface RuntimeSpawnRecord {
    id: string;
    px: number;
    py: number;
    pz: number;
    rx: number;
    ry: number;
    rz: number;
}
